apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fimd.clustergarage.io
  namespace: kube-system
  labels:
    daemon: fimd
spec:
  selector:
    matchLabels:
      daemon: fimd
  template:
    metadata:
      labels:
        daemon: fimd
    spec:
      #tolerations:
      #- key: node-role.kubernetes.io/master
      #  effect: NoSchedule
      containers:
      - name: fimd
        image: clustergarage/fimd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: fimd-svc
  namespace: kube-system
spec:
  type: NodePort
  selector:
    daemon: fimd
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
